version: '2'

services:
  mapstore-frontend:
    container_name: igrac-mapstore-frontend
    build: docker-mapstore

  nginx:
    container_name: igrac-mapstore-nginx
    image: nginx
    hostname: nginx
    volumes:
      - ./sites-enabled:/etc/nginx/conf.d:ro
    links:
      - mapstore-frontend:frontend
    ports:
      - "80:8081"
      - "4430:443"
    restart: unless-stopped